### ISSUE TITLE
Allow some inline HTML in Panel Heading

### ISSUE THREAD

**Issue by scharc** [filipstefansson/bootstrap-3-shortcodes#111]
I needed to add a <br> in a panel header, so I had to patch bs_panel() and removed the esc_html() in the heading routine. 

Could you push this in the next release? I think some inline elements make sense in the panel heading, like strong, em and br

**Comment by MWDelaney** [comment]
Hi, unfortunately because of the way panel titles are defined as a shortcode attribute, rather than as their own shortcode, it runs counter to the way we have designed this plugin to allow inline HTML in the shortcode attributes. We will perhaps look into splitting the panel, panel header, and panel footer into separate shortcodes in a future release, which would allow for some HTML and styling of the header.

Thanks!
